apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-oplp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-oplp
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-oplp
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-oplp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-oplp
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dhkq-tenant/rhtap-demo-app/hacbs-test-project-oplp@sha256:955c38818e35c1425d2ee85e47c6531141d68d365eeccdc737a0287092ea1750
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
